env:
  es2021: true
  node: true
extends: 
 - standard-with-typescript
 - plugin:n/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:
  {
    semi: 0,
    curly: 0,
    'comma-dangle': 0,
    'no-console': 0,
    'no-sequences': 0,
    '@typescript-eslint/comma-dangle': [2, "always-multiline"],
    '@typescript-eslint/semi': 0,
    '@typescript-eslint/strict-boolean-expressions': 0,
    '@typescript-eslint/return-await': 0,
    '@typescript-eslint/no-unused-vars': 1,
    '@typescript-eslint/prefer-nullish-coalescing': 0,
    '@typescript-eslint/promise-function-async': 0,
    '@typescript-eslint/no-invalid-void-type': 0,
    '@typescript-eslint/member-delimiter-style':
      [
        2,
        {
          'multiline': { 'delimiter': 'semi', 'requireLast': true },
          'singleline': { 'delimiter': 'semi', 'requireLast': false },
          'multilineDetection': 'brackets',
        },
      ],
  }
